#ifndef _PUBLIC_H_
#define _PUBLIC_H

#pragma once

#define GLOBAL_MYDRIVER_DEVICE_NAME		L"\\Device\\MyDriver"
#define GLOBAL_MYDRIVR_SYMBOLICLINK		L"\\DosDevices\\MyDriver"

#define GLOBAL_MYDRIVER_WIN32_NAMEW		L"\\\\.\\MyDriver"
#define GLOBAL_MYDRIVER_WIN32_NAMEA		"\\\\.\\MyDriver"
#ifdef _UNICODE
#define GLOBAL_MYDRIVER_WIN32_NAME	GLOBAL_MYDRIVER_WIN32_NAMEW
#else
#define GLOBAL_MYDRIVER_WIN32_NAME	GLOBAL_MYDRIVER_WIN32_NAMEA
#endif

#define IOCTL_INDEX (0x800 + 1)

#define IOCTL_MYDRIVER_START_THREAD  CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_INDEX, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_MYDRIVER_STOP_THREAD  CTL_CODE(FILE_DEVICE_UNKNOWN, IOCTL_INDEX + 0x001, METHOD_BUFFERED, FILE_ANY_ACCESS)


#endif
